In [1]:
import tensorflow as tf
import numpy as np






In [2]:
# this will be an int32 tensor by default ; see "dtpes" below
rank_0_tensor = tf.constant(4)
print(rank_0_tensor)

tf.Tensor(4, shape=(), dtype=int32)


In [3]:
rank_1_tensor=tf.constant([1.0,2.0,3.0])
print(rank_1_tensor)

tf.Tensor([1. 2. 3.], shape=(3,), dtype=float32)


In [4]:
rank_2_tensor=tf.constant([[1,2,3],[4,5,6],[7,8,9]])
print(rank_2_tensor)

tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32)


In [5]:
#There can be arbitrary number of dimensions
rank_3_tensor=tf.constant([[[1,2,3,3,4],[4,5,6,6,6]],[[4,5,6,6,6],[4,5,6,6,6]],[[4,5,6,6,6],[4,5,6,6,6]]])
print(rank_3_tensor)

tf.Tensor(
[[[1 2 3 3 4]
  [4 5 6 6 6]]

 [[4 5 6 6 6]
  [4 5 6 6 6]]

 [[4 5 6 6 6]
  [4 5 6 6 6]]], shape=(3, 2, 5), dtype=int32)


![Alt text](p.png)


In [6]:
np.array(rank_2_tensor)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
var1=tf.ones([3,4])
print(var1)


tf.Tensor(
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]], shape=(3, 4), dtype=float32)


In [8]:
var2=tf.zeros([2,3,4])
print(var2)

tf.Tensor(
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]], shape=(2, 3, 4), dtype=float32)


In [9]:
a=tf.constant([[1,2],[3,4]])
b=tf.constant([[5,6],[7,8]])
print(a+b)
print(tf.add(a,b))
print(a*b)
print(tf.multiply(a,b))
print(tf.matmul(a,b))  #matrix multiplication



tf.Tensor(
[[ 6  8]
 [10 12]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[ 6  8]
 [10 12]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[ 5 12]
 [21 32]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[ 5 12]
 [21 32]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32)


In [10]:
c=tf.constant([[4.0,5.0],[6.0,7.0]])

print(tf.reduce_sum(c))
print(tf.reduce_mean(c))
print(tf.reduce_max(c))
print(tf.reduce_min(c))
print(tf.argmax(c))
print(tf.argmin(c))
print(tf.nn.softmax(c))


tf.Tensor(22.0, shape=(), dtype=float32)


tf.Tensor(5.5, shape=(), dtype=float32)
tf.Tensor(7.0, shape=(), dtype=float32)
tf.Tensor(4.0, shape=(), dtype=float32)
tf.Tensor([1 1], shape=(2,), dtype=int64)
tf.Tensor([0 0], shape=(2,), dtype=int64)
tf.Tensor(
[[0.26894143 0.73105854]
 [0.26894143 0.73105854]], shape=(2, 2), dtype=float32)


In [11]:
tf.convert_to_tensor([1,2,4])


<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 4])>

In [12]:
rank_4_tensor=tf.zeros([2,3,4,5])
print(rank_4_tensor)

tf.Tensor(
[[[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]]


 [[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]]], shape=(2, 3, 4, 5), dtype=float32)


In [13]:
print("Type of every element:", rank_4_tensor.dtype)
print("Number of axis:", rank_4_tensor.ndim)
print("Shape of tensor:", rank_4_tensor.shape)
print("Elements along axis 0:", rank_4_tensor.shape[0])
print("Elements along last axis:", rank_4_tensor.shape[-1])
print("Total number of elements:", tf.size(rank_4_tensor).numpy())

Type of every element: <dtype: 'float32'>
Number of axis: 4
Shape of tensor: (2, 3, 4, 5)
Elements along axis 0: 2
Elements along last axis: 5
Total number of elements: 120


![Alt text](p1.png)

# indexing

In [14]:
rank_1_tensor=tf.constant([0,1,2,3,4,5,6,7,8,9])
print(rank_1_tensor)
print(rank_1_tensor.numpy())

tf.Tensor([0 1 2 3 4 5 6 7 8 9], shape=(10,), dtype=int32)
[0 1 2 3 4 5 6 7 8 9]


# sliching

In [15]:
# slicing concept
print ("Every element:", rank_1_tensor[:].numpy())
print ("First 5 elements:", rank_1_tensor[:5].numpy())
print ("Elements from index 5:", rank_1_tensor[5:].numpy())
print ("Elements from index 2 to 5:", rank_1_tensor[2:5].numpy())
print ("Elements from index 1 to 7 with step 2:", rank_1_tensor[1:7:2].numpy())
print ("Last element:", rank_1_tensor[-1].numpy())
print ("Last 3 elements:", rank_1_tensor[-3:].numpy())
print ("Reversed:", rank_1_tensor[::-1].numpy())
print("Before 4th element:", rank_1_tensor[:4].numpy())
print("From 4th element:", rank_1_tensor[4:].numpy())
print("Every other element:", rank_1_tensor[::2].numpy())

Every element: [0 1 2 3 4 5 6 7 8 9]
First 5 elements: [0 1 2 3 4]
Elements from index 5: [5 6 7 8 9]
Elements from index 2 to 5: [2 3 4]
Elements from index 1 to 7 with step 2: [1 3 5]
Last element: 9
Last 3 elements: [7 8 9]
Reversed: [9 8 7 6 5 4 3 2 1 0]
Before 4th element: [0 1 2 3]
From 4th element: [4 5 6 7 8 9]
Every other element: [0 2 4 6 8]


# Manipulating Shapes

In [16]:
# Shape returns a 'TensorShape' object that shows the size of alonng exis
x=tf.constant([[1],[2],[3]])
print(x)
print(x.shape)

tf.Tensor(
[[1]
 [2]
 [3]], shape=(3, 1), dtype=int32)
(3, 1)


In [17]:
print(tf.reshape(rank_3_tensor,[-1]))#flattening


tf.Tensor([1 2 3 3 4 4 5 6 6 6 4 5 6 6 6 4 5 6 6 6 4 5 6 6 6 4 5 6 6 6], shape=(30,), dtype=int32)


In [18]:
print(tf.reshape(rank_3_tensor,[6,5]))#reshaping to 2D tensor
print(tf.reshape (rank_3_tensor,[3,-1]))#reshaping to 3D tensor

tf.Tensor(
[[1 2 3 3 4]
 [4 5 6 6 6]
 [4 5 6 6 6]
 [4 5 6 6 6]
 [4 5 6 6 6]
 [4 5 6 6 6]], shape=(6, 5), dtype=int32)
tf.Tensor(
[[1 2 3 3 4 4 5 6 6 6]
 [4 5 6 6 6 4 5 6 6 6]
 [4 5 6 6 6 4 5 6 6 6]], shape=(3, 10), dtype=int32)


In [21]:
# bad examplez:dont do this
# YOU CANT REORERTHE ELEMENTS WHILE RESHAPING
print(tf.reshape(rank_3_tensor,[5,6]))#reshaping to 2D tensor
try:
    print(tf.reshape (rank_3_tensor,[8,4]))#reshaping to 3D tensor
except Exception as e:
    print(e)    
# YOU CANT REORERTHE ELEMENTS WHILE RESHAPING




tf.Tensor(
[[1 2 3 3 4 4]
 [5 6 6 6 4 5]
 [6 6 6 4 5 6]
 [6 6 4 5 6 6]
 [6 4 5 6 6 6]], shape=(5, 6), dtype=int32)
{{function_node __wrapped__Reshape_device_/job:localhost/replica:0/task:0/device:CPU:0}} Input to reshape is a tensor with 30 values, but the requested shape has 32 [Op:Reshape]


# MORE ON DTYPES

In [22]:
the_f64_tensor=tf.constant([1.0,2.0,3.0],dtype=tf.float64)
print(the_f64_tensor)
the_f16_tensor=tf.cast(the_f64_tensor,dtype=tf.float16)
print(the_f16_tensor)
the_u8_tensor=tf.cast(the_f16_tensor,dtype=tf.uint8)
print(the_u8_tensor)


tf.Tensor([1. 2. 3.], shape=(3,), dtype=float64)
tf.Tensor([1. 2. 3.], shape=(3,), dtype=float16)
tf.Tensor([1 2 3], shape=(3,), dtype=uint8)


# Broadcasting
In TensorFlow, broadcasting refers to the ability of tensors with different shapes to be automatically expanded to have compatible shapes during arithmetic operations. This allows operations to be performed element-wise without explicitly reshaping the tensors.

Rules for Broadcasting:
Dimensions must be equal or one of them must be 1:
If the dimensions of two tensors are not the same, TensorFlow will try to match them by "stretching" dimensions with size 1 to match the other tensor's size.
Alignment starts from the rightmost dimensions:
TensorFlow compares dimensions from the rightmost side and applies broadcasting rules.

In [ ]:
import tensorflow as tf

# Tensor with shape (3, 1)
a = tf.constant([[1], [2], [3]])

# Tensor with shape (1, 4)
b = tf.constant([[1, 2, 3, 4]])

# Broadcasting allows element-wise addition
result = a + b
print(result)

In [23]:
import tensorflow as tf

# Tensor with shape (3, 1)
a = tf.constant([[1], [2], [3]])

# Tensor with shape (1, 4)
b = tf.constant([[1, 2, 3, 4]])

# Broadcasting allows element-wise addition
result = a + b
print(result)

tf.Tensor(
[[2 3 4 5]
 [3 4 5 6]
 [4 5 6 7]], shape=(3, 4), dtype=int32)


# Ragged Tensor
A Ragged Tensor in TensorFlow is a tensor with variable-length dimensions, meaning that the rows (or other dimensions) can have different lengths. This is useful for representing data like sequences, where each sequence may have a different number of elements.

Key Features of Ragged Tensors:
They allow for efficient storage and processing of non-uniform data.
They are represented using tf.ragged.RaggedTensor.

In [30]:
ragged_list = ([
    [1, 2, 3],
    [4, 5], 
    [6], 
    [7, 8, 9, 10]])


In [32]:
ragged_tensor =tf.ragged.constant(ragged_list)
print(ragged_tensor)

<tf.RaggedTensor [[1, 2, 3], [4, 5], [6], [7, 8, 9, 10]]>


# string tensor
A string tensor in TensorFlow is a tensor that holds string data. Unlike numerical tensors, string tensors can store variable-length strings, making them useful for handling text data, categorical data, or any other non-numeric information.

Key Features of String Tensors:
Variable Length: Strings in a tensor can have different lengths.
Immutable: Like all tensors in TensorFlow, string tensors are immutable, meaning their values cannot be changed after creation.
Supported Operations: TensorFlow provides various operations for string manipulation, such as splitting, joining, and formatting.
Creating a String Tensor:
You can create a string tensor using tf.constant: