In [3]:
import tensorflow as tf
import numpy as np






In [4]:
# this will be an int32 tensor by default ; see "dtpes" below
rank_0_tensor = tf.constant(4)
print(rank_0_tensor)

tf.Tensor(4, shape=(), dtype=int32)


In [5]:
rank_1_tensor=tf.constant([1.0,2.0,3.0])
print(rank_1_tensor)

tf.Tensor([1. 2. 3.], shape=(3,), dtype=float32)


In [6]:
rank_2_tensor=tf.constant([[1,2,3],[4,5,6],[7,8,9]])
print(rank_2_tensor)

tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32)


In [7]:
#There can be arbitrary number of dimensions
rank_3_tensor=tf.constant([[[1,2,3,3,4],[4,5,6,6,6]],[[4,5,6,6,6],[4,5,6,6,6]],[[4,5,6,6,6],[4,5,6,6,6]]])
print(rank_3_tensor)

tf.Tensor(
[[[1 2 3 3 4]
  [4 5 6 6 6]]

 [[4 5 6 6 6]
  [4 5 6 6 6]]

 [[4 5 6 6 6]
  [4 5 6 6 6]]], shape=(3, 2, 5), dtype=int32)


![Alt text](p.png)


In [8]:
np.array(rank_2_tensor)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
var1=tf.ones([3,4])
print(var1)


tf.Tensor(
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]], shape=(3, 4), dtype=float32)


In [10]:
var2=tf.zeros([2,3,4])
print(var2)

tf.Tensor(
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]], shape=(2, 3, 4), dtype=float32)


In [11]:
a=tf.constant([[1,2],[3,4]])
b=tf.constant([[5,6],[7,8]])
print(a+b)
print(tf.add(a,b))
print(a*b)
print(tf.multiply(a,b))
print(tf.matmul(a,b))  #matrix multiplication



tf.Tensor(
[[ 6  8]
 [10 12]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[ 6  8]
 [10 12]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[ 5 12]
 [21 32]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[ 5 12]
 [21 32]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32)


In [12]:
c=tf.constant([[4.0,5.0],[6.0,7.0]])

print(tf.reduce_sum(c))
print(tf.reduce_mean(c))
print(tf.reduce_max(c))
print(tf.reduce_min(c))
print(tf.argmax(c))
print(tf.argmin(c))
print(tf.nn.softmax(c))


tf.Tensor(22.0, shape=(), dtype=float32)
tf.Tensor(5.5, shape=(), dtype=float32)
tf.Tensor(7.0, shape=(), dtype=float32)
tf.Tensor(4.0, shape=(), dtype=float32)
tf.Tensor([1 1], shape=(2,), dtype=int64)
tf.Tensor([0 0], shape=(2,), dtype=int64)
tf.Tensor(
[[0.26894143 0.73105854]
 [0.26894143 0.73105854]], shape=(2, 2), dtype=float32)


In [13]:
tf.convert_to_tensor([1,2,4])


<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 4])>

In [14]:
rank_4_tensor=tf.zeros([2,3,4,5])
print(rank_4_tensor)

tf.Tensor(
[[[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]]


 [[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]]], shape=(2, 3, 4, 5), dtype=float32)


In [15]:
print("Type of every element:", rank_4_tensor.dtype)
print("Number of axis:", rank_4_tensor.ndim)
print("Shape of tensor:", rank_4_tensor.shape)
print("Elements along axis 0:", rank_4_tensor.shape[0])
print("Elements along last axis:", rank_4_tensor.shape[-1])
print("Total number of elements:", tf.size(rank_4_tensor).numpy())

Type of every element: <dtype: 'float32'>
Number of axis: 4
Shape of tensor: (2, 3, 4, 5)
Elements along axis 0: 2
Elements along last axis: 5
Total number of elements: 120


![Alt text](p1.png)

# indexing

In [16]:
rank_1_tensor=tf.constant([0,1,2,3,4,5,6,7,8,9])
print(rank_1_tensor)
print(rank_1_tensor.numpy())

tf.Tensor([0 1 2 3 4 5 6 7 8 9], shape=(10,), dtype=int32)
[0 1 2 3 4 5 6 7 8 9]


# sliching

In [18]:
# slicing concept
print ("Every element:", rank_1_tensor[:].numpy())
print ("First 5 elements:", rank_1_tensor[:5].numpy())
print ("Elements from index 5:", rank_1_tensor[5:].numpy())
print ("Elements from index 2 to 5:", rank_1_tensor[2:5].numpy())
print ("Elements from index 1 to 7 with step 2:", rank_1_tensor[1:7:2].numpy())
print ("Last element:", rank_1_tensor[-1].numpy())
print ("Last 3 elements:", rank_1_tensor[-3:].numpy())
print ("Reversed:", rank_1_tensor[::-1].numpy())
print("Before 4th element:", rank_1_tensor[:4].numpy())
print("From 4th element:", rank_1_tensor[4:].numpy())
print("Every other element:", rank_1_tensor[::2].numpy())

Every element: [0 1 2 3 4 5 6 7 8 9]
First 5 elements: [0 1 2 3 4]
Elements from index 5: [5 6 7 8 9]
Elements from index 2 to 5: [2 3 4]
Elements from index 1 to 7 with step 2: [1 3 5]
Last element: 9
Last 3 elements: [7 8 9]
Reversed: [9 8 7 6 5 4 3 2 1 0]
Before 4th element: [0 1 2 3]
From 4th element: [4 5 6 7 8 9]
Every other element: [0 2 4 6 8]
